apiVersion: v1
kind: Service
metadata:
  name: tici-meta
  namespace: ${NAMESPACE}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: server
    port: 8500
    protocol: TCP
    targetPort: 8500
  - name: status
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/component: tici-meta
  sessionAffinity: None
  type: ClusterIP
