apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: tici-meta
  name: tici-meta
  namespace: ${NAMESPACE}
spec:
  replicas: ${TICI_META_REPLICAS}
  selector:
    matchLabels:
      app.kubernetes.io/component: tici-meta
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "yes"
        prometheus.io/path: /metrics
        prometheus.io/port: "8501"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/component: tici-meta
    spec:
      containers:
      - command:
        - /tici-server
        - meta
        - --config
        - /etc/tici-meta/config.toml
        - --log-file=
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: db
        - name: TZ
          value: UTC
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: ${TICI_IMAGE}
        imagePullPolicy: Always
        #imagePullPolicy: Always
        name: tici-meta
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8501
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tici-meta
          name: config
          readOnly: true
        - mountPath: /tmp
          name: tmp-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: controller
      serviceAccountName: controller
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: tici-meta-config
        name: config
      - emptyDir: {}
        name: tmp-volume
