apiVersion: v1
kind: Service
metadata:
  name: tici-worker-peer
  namespace: ${NAMESPACE}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: server
    port: 8510
    protocol: TCP
    targetPort: 8510
  - name: status
    port: 8511
    protocol: TCP
    targetPort: 8511
  selector:
    app.kubernetes.io/component: tici-worker
    app.kubernetes.io/instance: tici-worker
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None
